# Generated by Django 2.2.10 on 2020-03-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='href',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
